// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"false","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"10","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"SkipTitle","status":true,"description":"v1.00 Skips Title Screen\r\n<SilverSkipTitle>","parameters":{"Skip Title Screen Entirely":"true","Skip If Savefile Present":"true","FadeOut Title":"true"}},
{"name":"Screen Resolution","status":true,"description":"v1.00 Change your game's screen resolution to your liking!","parameters":{"Screen Width":"816","Screen Height":"624"}}
];
